### ISSUE TITLE
Fluid heights and widths for SVGs

### ISSUE THREAD

**Issue by zoetrope69** [meandavejustice/draw-wave#1]
One good thing about SVGs are how they're responsive, if the waves generated could be based on fluid units such as percentages then it'd still retain this.

I may be wrong about how this is set-up?

e.g The wave would fit to a containing element.

what you think?

**Comment by zoetrope69** [comment]
Think this is missing a `viewBox` tag for it to scale properly? https://css-tricks.com/scale-svg/

**Comment by zoetrope69** [comment]
Closed as I don't want to manage/update on this. Can you reopen your own issue please.

**Comment by meandavejustice** [comment]
@zaccolley I made another issue, in the future you should unwatch an issue instead of closing unfixed bugs on repos that are not your own
